// Copyright 1998-2017 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "STypes.h"
#include "EmbedList.generated.h"

UCLASS()
class UEmbedList : public UObject
{
	GENERATED_UCLASS_BODY()

	virtual ~UEmbedList();

public:
	TArray<FEmbedListMember> asset_list;
	
//	FName EMBED_MAPS_ORZ_COMMONS_MAP;
// 	FName EMBED_MAPS_ORZ_DUSTTOWN_MAP;
// 	FName EMBED_MAPS_Q1M1_MAP;
// 	FName EMBED_MAPS_Q2M1_MAP;
// 	FName EMBED_MAPS_Q2M2_MAP;
// 	FName EMBED_MAPS_Q2M3_MAP;
// 	FName EMBED_MAPS_Q3M1_GENLOCK_MAP;
// 	FName EMBED_MAPS_Q3M2_BANDITS_MAP;
// 	FName EMBED_MAPS_Q4M1_MAP;
// 	FName EMBED_MAPS_Q4M2_MAP;
// 	FName EMBED_MAPS_Q4M3_MAP;
// 	FName EMBED_MAPS_Q4M4_MAP;
// 	FName EMBED_MAPS_TUT_AREA_MAP;
 	FName EMBED_MAPS_TUT_AREA2_MAP;
// 	FName EMBED_ASSETS_DF_LEATHER_SWF;
// 	FName EMBED_ASSETS_DF_MAIL_SWF;
// 	FName EMBED_ASSETS_DW_LEATHER_SWF;
// 	FName EMBED_ASSETS_DW_MAIL_SWF;
// 	FName EMBED_ASSETS_HF_CLOTH_SWF;
// 	FName EMBED_ASSETS_HF_LEATHER2_SWF;
// 	FName EMBED_ASSETS_HF_LEATHER_SWF;
// 	FName EMBED_ASSETS_HF_MAIL2_SWF;
// 	FName EMBED_ASSETS_HF_MAIL_SWF;
// 	FName EMBED_ASSETS_HM_CLOTH_SWF;
// 	FName EMBED_ASSETS_HM_LEATHER2_SWF;
// 	FName EMBED_ASSETS_HM_LEATHER_SWF;
// 	FName EMBED_ASSETS_HM_MAIL2_SWF;
// 	FName EMBED_ASSETS_HM_MAIL_SWF;
// 	FName EMBED_ASSETS_M_BANDIT_SWF;
// 	FName EMBED_ASSETS_M_DEEP_STALKER_SWF;
// 	FName EMBED_ASSETS_M_GENLOCK_SWF;
// 	FName EMBED_ASSETS_M_HURLOCK_SWF;
// 	FName EMBED_ASSETS_M_OGRE_SWF;
// 	FName EMBED_ASSETS_M_SPIDER_GIANT_SWF;
// 	FName EMBED_TUTORIALS_XML;
// 	FName EMBED_CONVIDS_XML;
 	FName EMBED_GAMEDATA_XML;
// 	FName EMBED_DIALOGUES_CONV_ALLDEAD_TXT;
// 	FName EMBED_DIALOGUES_CONV_BANDIT2_TXT;
// 	FName EMBED_DIALOGUES_CONV_BANDIT_TXT;
// 	FName EMBED_DIALOGUES_CONV_BARD_TXT;
// 	FName EMBED_DIALOGUES_CONV_BARD2_TXT;
// 	FName EMBED_DIALOGUES_CONV_BARD3_TXT;
// 	FName EMBED_DIALOGUES_CONV_BARD_REJOIN_TXT;
// 	FName EMBED_DIALOGUES_CONV_CAPTAIN_TXT;
// 	FName EMBED_DIALOGUES_CONV_CAPTAIN2_TXT;
// 	FName EMBED_DIALOGUES_CONV_COMMONS_TO_DUSTTOWN_TXT;
// 	FName EMBED_DIALOGUES_CONV_CRIMELORD2_TXT;
// 	FName EMBED_DIALOGUES_CONV_CRIMELORD3_TXT;
// 	FName EMBED_DIALOGUES_CONV_CRIMELORD4_TXT;
// 	FName EMBED_DIALOGUES_CONV_CRIMELORD5_TXT;
// 	FName EMBED_DIALOGUES_CONV_CRIMELORD_COMMONS_TXT;
// 	FName EMBED_DIALOGUES_CONV_DEAD_SMUGGLERS_TXT;
// 	FName EMBED_DIALOGUES_CONV_DUSTTOWN_TXT;
// 	FName EMBED_DIALOGUES_CONV_EMISSARY_MINE_TXT;
// 	FName EMBED_DIALOGUES_CONV_EMISSARY_MINE_DEFEATED_TXT;
// 	FName EMBED_DIALOGUES_CONV_FIRST_MACHINE_TXT;
// 	FName EMBED_DIALOGUES_CONV_GREYWARDEN2_TXT;
// 	FName EMBED_DIALOGUES_CONV_GREYWARDEN_TXT;
// 	FName EMBED_DIALOGUES_CONV_HEALER_TXT;
// 	FName EMBED_DIALOGUES_CONV_HEALER_REJOIN_TXT;
// 	FName EMBED_DIALOGUES_CONV_LEAVING_ORZAMMAR_COMMONS_TXT;
// 	FName EMBED_DIALOGUES_CONV_LEAVING_QUEST_AREA_TXT;
// 	FName EMBED_DIALOGUES_CONV_LOWLYSOLDIER2_TXT;
// 	FName EMBED_DIALOGUES_CONV_LOWLYSOLDIER3_TXT;
// 	FName EMBED_DIALOGUES_CONV_LOWLYSOLDIER4_TXT;
// 	FName EMBED_DIALOGUES_CONV_LOWLYSOLDIER_TXT;
// 	FName EMBED_DIALOGUES_CONV_MILITARYLEADER2_TXT;
// 	FName EMBED_DIALOGUES_CONV_MILITARYLEADER3_TXT;
// 	FName EMBED_DIALOGUES_CONV_MILITARYLEADER_TXT;
// 	FName EMBED_DIALOGUES_CONV_MILITARYLEADER_WAITING_FOR_WARDEN_TXT;
// 	FName EMBED_DIALOGUES_CONV_NOBLE3_TXT;
// 	FName EMBED_DIALOGUES_CONV_NOBLE2_TXT;
// 	FName EMBED_DIALOGUES_CONV_NOBLE_TXT;
// 	FName EMBED_DIALOGUES_CONV_NOBLE_DURING_GENLOCK_QUEST_TXT;
// 	FName EMBED_DIALOGUES_CONV_ORIGIN2_TXT;
// 	FName EMBED_DIALOGUES_CONV_ORIGIN_TXT;
// 	FName EMBED_DIALOGUES_CONV_PUB2_TXT;
// 	FName EMBED_DIALOGUES_CONV_PUB_TXT;
// 	FName EMBED_DIALOGUES_CONV_PUNK_DUST_TXT;
// 	FName EMBED_DIALOGUES_CONV_SCENE4_TXT;
// 	FName EMBED_DIALOGUES_CONV_SEARCH_TXT;
// 	FName EMBED_DIALOGUES_CONV_SECOND_MACHINE_TXT;
// 	FName EMBED_DIALOGUES_CONV_THIRD_MACHINE_TXT;
// 	FName EMBED_DIALOGUES_CONV_TOOWEAK_TXT;
// 	FName EMBED_DIALOGUES_CONV_TUTORIAL2_TXT;
// 	FName EMBED_DIALOGUES_CONV_TUTORIAL_TXT;
// 	FName EMBED_DIALOGUES_CONV_WARDEN_REJOIN_TXT;
// 	FName EMBED_DIALOGUES_INNKEEPER_COMMONS_TXT;
// 	FName EMBED_DIALOGUES_INNKEEPER_DUST_TXT;
// 	FName EMBED_DIALOGUES_SHOP_COMMONS_BLACKSMITH_TXT;
// 	FName EMBED_DIALOGUES_SHOP_COMMONS_STALL_TXT;
// 	FName EMBED_DIALOGUES_SHOP_COMMONS_POTIONS_TXT;
// 	FName EMBED_DIALOGUES_SHOP_DUST_BLACKSMITH_TXT;
// 	FName EMBED_DIALOGUES_SHOP_DUST_STALL_TXT;

	const bool EMBED_ENABLED = true;
};



