#pragma once

const float WEAPON_DWARF_BOW_SCALE_Y = 0.727;//TODO not needed?
const int32 WEAPON_GREATAXE_ORNATE = 1;
const int32 WEAPON_GREATAXE_DWARF = 2;
const int32 WEAPON_GREATSWORD_NICE = 3;
const int32 WEAPON_GREATSWORD_NASTY = 4;
const int32 WEAPON_SWORD_DARKSPAWN = 5;
const int32 WEAPON_AXE_DARKSPAWN = 6;
const int32 WEAPON_SWORD_STANDARD = 1;
const int32 WEAPON_SWORD_HILTLESS = 2;
const int32 WEAPON_MACE_CHUNKY = 3;
const int32 WEAPON_MACE_SPIKY = 4;
const int32 WEAPON_AXE_HATCHET = 5;
const int32 WEAPON_AXE_DWARF = 6;
const int32 WEAPON_DAGGER_STRAIGHT = 7;
const int32 WEAPON_DAGGER_CURVY = 8;
const int32 WEAPON_SWORD_ANCIENT = 9;
const int32 WEAPON_STAFF_BULBOUS = 1;
const int32 WEAPON_STAFF_TWISTY = 2;
const int32 WEAPON_STAFF_TRIDENT = 3;
const int32 WEAPON_BOW_LONG = 1;
const int32 WEAPON_BOW_TWISTY = 2;