#include "EmbedList.h"

UEmbedList::UEmbedList(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
//	EMBED_MAPS_ORZ_COMMONS_MAP = "EmbedList_EMBED_MAPS_ORZ_COMMONS_MAP";
// 	EMBED_MAPS_ORZ_DUSTTOWN_MAP = "EmbedList_EMBED_MAPS_ORZ_DUSTTOWN_MAP";
// 	EMBED_MAPS_Q1M1_MAP = "EmbedList_EMBED_MAPS_Q1M1_MAP";
// 	EMBED_MAPS_Q2M1_MAP = "EmbedList_EMBED_MAPS_Q2M1_MAP";
// 	EMBED_MAPS_Q2M2_MAP = "EmbedList_EMBED_MAPS_Q2M2_MAP";
// 	EMBED_MAPS_Q2M3_MAP = "EmbedList_EMBED_MAPS_Q2M3_MAP";
// 	EMBED_MAPS_Q3M1_GENLOCK_MAP = "EmbedList_EMBED_MAPS_Q3M1_GENLOCK_MAP";
// 	EMBED_MAPS_Q3M2_BANDITS_MAP = "EmbedList_EMBED_MAPS_Q3M2_BANDITS_MAP";
// 	EMBED_MAPS_Q4M1_MAP = "EmbedList_EMBED_MAPS_Q4M1_MAP";
// 	EMBED_MAPS_Q4M2_MAP = "EmbedList_EMBED_MAPS_Q4M2_MAP";
// 	EMBED_MAPS_Q4M3_MAP = "EmbedList_EMBED_MAPS_Q4M3_MAP";
// 	EMBED_MAPS_Q4M4_MAP = "EmbedList_EMBED_MAPS_Q4M4_MAP";
// 	EMBED_MAPS_TUT_AREA_MAP = "EmbedList_EMBED_MAPS_TUT_AREA_MAP";
 	EMBED_MAPS_TUT_AREA2_MAP = "EmbedList_EMBED_MAPS_TUT_AREA2_MAP";
// 	EMBED_ASSETS_DF_LEATHER_SWF = "EmbedList_EMBED_ASSETS_DF_LEATHER_SWF";
// 	EMBED_ASSETS_DF_MAIL_SWF = "EmbedList_EMBED_ASSETS_DF_MAIL_SWF";
// 	EMBED_ASSETS_DW_LEATHER_SWF = "EmbedList_EMBED_ASSETS_DW_LEATHER_SWF";
// 	EMBED_ASSETS_DW_MAIL_SWF = "EmbedList_EMBED_ASSETS_DW_MAIL_SWF";
// 	EMBED_ASSETS_HF_CLOTH_SWF = "EmbedList_EMBED_ASSETS_HF_CLOTH_SWF";
// 	EMBED_ASSETS_HF_LEATHER2_SWF = "EmbedList_EMBED_ASSETS_HF_LEATHER2_SWF";
// 	EMBED_ASSETS_HF_LEATHER_SWF = "EmbedList_EMBED_ASSETS_HF_LEATHER_SWF";
// 	EMBED_ASSETS_HF_MAIL2_SWF = "EmbedList_EMBED_ASSETS_HF_MAIL2_SWF";
// 	EMBED_ASSETS_HF_MAIL_SWF = "EmbedList_EMBED_ASSETS_HF_MAIL_SWF";
// 	EMBED_ASSETS_HM_CLOTH_SWF = "EmbedList_EMBED_ASSETS_HM_CLOTH_SWF";
// 	EMBED_ASSETS_HM_LEATHER2_SWF = "EmbedList_EMBED_ASSETS_HM_LEATHER2_SWF";
// 	EMBED_ASSETS_HM_LEATHER_SWF = "EmbedList_EMBED_ASSETS_HM_LEATHER_SWF";
// 	EMBED_ASSETS_HM_MAIL2_SWF = "EmbedList_EMBED_ASSETS_HM_MAIL2_SWF";
// 	EMBED_ASSETS_HM_MAIL_SWF = "EmbedList_EMBED_ASSETS_HM_MAIL_SWF";
// 	EMBED_ASSETS_M_BANDIT_SWF = "EmbedList_EMBED_ASSETS_M_BANDIT_SWF";
// 	EMBED_ASSETS_M_DEEP_STALKER_SWF = "EmbedList_EMBED_ASSETS_M_DEEP_STALKER_SWF";
// 	EMBED_ASSETS_M_GENLOCK_SWF = "EmbedList_EMBED_ASSETS_M_GENLOCK_SWF";
// 	EMBED_ASSETS_M_HURLOCK_SWF = "EmbedList_EMBED_ASSETS_M_HURLOCK_SWF";
// 	EMBED_ASSETS_M_OGRE_SWF = "EmbedList_EMBED_ASSETS_M_OGRE_SWF";
// 	EMBED_ASSETS_M_SPIDER_GIANT_SWF = "EmbedList_EMBED_ASSETS_M_SPIDER_GIANT_SWF";
// 	EMBED_TUTORIALS_XML = "EmbedList_EMBED_TUTORIALS_XML";
// 	EMBED_CONVIDS_XML = "EmbedList_EMBED_CONVIDS_XML";
 	EMBED_GAMEDATA_XML = "EmbedList_EMBED_GAMEDATA_XML";
// 	EMBED_DIALOGUES_CONV_ALLDEAD_TXT = "EmbedList_EMBED_DIALOGUES_CONV_ALLDEAD_TXT";
// 	EMBED_DIALOGUES_CONV_BANDIT2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_BANDIT2_TXT";
// 	EMBED_DIALOGUES_CONV_BANDIT_TXT = "EmbedList_EMBED_DIALOGUES_CONV_BANDIT_TXT";
// 	EMBED_DIALOGUES_CONV_BARD_TXT = "EmbedList_EMBED_DIALOGUES_CONV_BARD_TXT";
// 	EMBED_DIALOGUES_CONV_BARD2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_BARD2_TXT";
// 	EMBED_DIALOGUES_CONV_BARD3_TXT = "EmbedList_EMBED_DIALOGUES_CONV_BARD3_TXT";
// 	EMBED_DIALOGUES_CONV_BARD_REJOIN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_BARD_REJOIN_TXT";
// 	EMBED_DIALOGUES_CONV_CAPTAIN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CAPTAIN_TXT";
// 	EMBED_DIALOGUES_CONV_CAPTAIN2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CAPTAIN2_TXT";
// 	EMBED_DIALOGUES_CONV_COMMONS_TO_DUSTTOWN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_COMMONS_TO_DUSTTOWN_TXT";
// 	EMBED_DIALOGUES_CONV_CRIMELORD2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CRIMELORD2_TXT";
// 	EMBED_DIALOGUES_CONV_CRIMELORD3_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CRIMELORD3_TXT";
// 	EMBED_DIALOGUES_CONV_CRIMELORD4_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CRIMELORD4_TXT";
// 	EMBED_DIALOGUES_CONV_CRIMELORD5_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CRIMELORD5_TXT";
// 	EMBED_DIALOGUES_CONV_CRIMELORD_COMMONS_TXT = "EmbedList_EMBED_DIALOGUES_CONV_CRIMELORD_COMMONS_TXT";
// 	EMBED_DIALOGUES_CONV_DEAD_SMUGGLERS_TXT = "EmbedList_EMBED_DIALOGUES_CONV_DEAD_SMUGGLERS_TXT";
// 	EMBED_DIALOGUES_CONV_DUSTTOWN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_DUSTTOWN_TXT";
// 	EMBED_DIALOGUES_CONV_EMISSARY_MINE_TXT = "EmbedList_EMBED_DIALOGUES_CONV_EMISSARY_MINE_TXT";
// 	EMBED_DIALOGUES_CONV_EMISSARY_MINE_DEFEATED_TXT = "EmbedList_EMBED_DIALOGUES_CONV_EMISSARY_MINE_DEFEATED_TXT";
// 	EMBED_DIALOGUES_CONV_FIRST_MACHINE_TXT = "EmbedList_EMBED_DIALOGUES_CONV_FIRST_MACHINE_TXT";
// 	EMBED_DIALOGUES_CONV_GREYWARDEN2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_GREYWARDEN2_TXT";
// 	EMBED_DIALOGUES_CONV_GREYWARDEN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_GREYWARDEN_TXT";
// 	EMBED_DIALOGUES_CONV_HEALER_TXT = "EmbedList_EMBED_DIALOGUES_CONV_HEALER_TXT";
// 	EMBED_DIALOGUES_CONV_HEALER_REJOIN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_HEALER_REJOIN_TXT";
// 	EMBED_DIALOGUES_CONV_LEAVING_ORZAMMAR_COMMONS_TXT = "EmbedList_EMBED_DIALOGUES_CONV_LEAVING_ORZAMMAR_COMMONS_TXT";
// 	EMBED_DIALOGUES_CONV_LEAVING_QUEST_AREA_TXT = "EmbedList_EMBED_DIALOGUES_CONV_LEAVING_QUEST_AREA_TXT";
// 	EMBED_DIALOGUES_CONV_LOWLYSOLDIER2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_LOWLYSOLDIER2_TXT";
// 	EMBED_DIALOGUES_CONV_LOWLYSOLDIER3_TXT = "EmbedList_EMBED_DIALOGUES_CONV_LOWLYSOLDIER3_TXT";
// 	EMBED_DIALOGUES_CONV_LOWLYSOLDIER4_TXT = "EmbedList_EMBED_DIALOGUES_CONV_LOWLYSOLDIER4_TXT";
// 	EMBED_DIALOGUES_CONV_LOWLYSOLDIER_TXT = "EmbedList_EMBED_DIALOGUES_CONV_LOWLYSOLDIER_TXT";
// 	EMBED_DIALOGUES_CONV_MILITARYLEADER2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_MILITARYLEADER2_TXT";
// 	EMBED_DIALOGUES_CONV_MILITARYLEADER3_TXT = "EmbedList_EMBED_DIALOGUES_CONV_MILITARYLEADER3_TXT";
// 	EMBED_DIALOGUES_CONV_MILITARYLEADER_TXT = "EmbedList_EMBED_DIALOGUES_CONV_MILITARYLEADER_TXT";
// 	EMBED_DIALOGUES_CONV_MILITARYLEADER_WAITING_FOR_WARDEN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_MILITARYLEADER_WAITING_FOR_WARDEN_TXT";
// 	EMBED_DIALOGUES_CONV_NOBLE3_TXT = "EmbedList_EMBED_DIALOGUES_CONV_NOBLE3_TXT";
// 	EMBED_DIALOGUES_CONV_NOBLE2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_NOBLE2_TXT";
// 	EMBED_DIALOGUES_CONV_NOBLE_TXT = "EmbedList_EMBED_DIALOGUES_CONV_NOBLE_TXT";
// 	EMBED_DIALOGUES_CONV_NOBLE_DURING_GENLOCK_QUEST_TXT = "EmbedList_EMBED_DIALOGUES_CONV_NOBLE_DURING_GENLOCK_QUEST_TXT";
// 	EMBED_DIALOGUES_CONV_ORIGIN2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_ORIGIN2_TXT";
// 	EMBED_DIALOGUES_CONV_ORIGIN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_ORIGIN_TXT";
// 	EMBED_DIALOGUES_CONV_PUB2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_PUB2_TXT";
// 	EMBED_DIALOGUES_CONV_PUB_TXT = "EmbedList_EMBED_DIALOGUES_CONV_PUB_TXT";
// 	EMBED_DIALOGUES_CONV_PUNK_DUST_TXT = "EmbedList_EMBED_DIALOGUES_CONV_PUNK_DUST_TXT";
// 	EMBED_DIALOGUES_CONV_SCENE4_TXT = "EmbedList_EMBED_DIALOGUES_CONV_SCENE4_TXT";
// 	EMBED_DIALOGUES_CONV_SEARCH_TXT = "EmbedList_EMBED_DIALOGUES_CONV_SEARCH_TXT";
// 	EMBED_DIALOGUES_CONV_SECOND_MACHINE_TXT = "EmbedList_EMBED_DIALOGUES_CONV_SECOND_MACHINE_TXT";
// 	EMBED_DIALOGUES_CONV_THIRD_MACHINE_TXT = "EmbedList_EMBED_DIALOGUES_CONV_THIRD_MACHINE_TXT";
// 	EMBED_DIALOGUES_CONV_TOOWEAK_TXT = "EmbedList_EMBED_DIALOGUES_CONV_TOOWEAK_TXT";
// 	EMBED_DIALOGUES_CONV_TUTORIAL2_TXT = "EmbedList_EMBED_DIALOGUES_CONV_TUTORIAL2_TXT";
// 	EMBED_DIALOGUES_CONV_TUTORIAL_TXT = "EmbedList_EMBED_DIALOGUES_CONV_TUTORIAL_TXT";
// 	EMBED_DIALOGUES_CONV_WARDEN_REJOIN_TXT = "EmbedList_EMBED_DIALOGUES_CONV_WARDEN_REJOIN_TXT";
// 	EMBED_DIALOGUES_INNKEEPER_COMMONS_TXT = "EmbedList_EMBED_DIALOGUES_INNKEEPER_COMMONS_TXT";
// 	EMBED_DIALOGUES_INNKEEPER_DUST_TXT = "EmbedList_EMBED_DIALOGUES_INNKEEPER_DUST_TXT";
// 	EMBED_DIALOGUES_SHOP_COMMONS_BLACKSMITH_TXT = "EmbedList_EMBED_DIALOGUES_SHOP_COMMONS_BLACKSMITH_TXT";
// 	EMBED_DIALOGUES_SHOP_COMMONS_STALL_TXT = "EmbedList_EMBED_DIALOGUES_SHOP_COMMONS_STALL_TXT";
// 	EMBED_DIALOGUES_SHOP_COMMONS_POTIONS_TXT = "EmbedList_EMBED_DIALOGUES_SHOP_COMMONS_POTIONS_TXT";
// 	EMBED_DIALOGUES_SHOP_DUST_BLACKSMITH_TXT = "EmbedList_EMBED_DIALOGUES_SHOP_DUST_BLACKSMITH_TXT";
// 	EMBED_DIALOGUES_SHOP_DUST_STALL_TXT = "EmbedList_EMBED_DIALOGUES_SHOP_DUST_STALL_TXT";

//	asset_list.Add({ "maps/orz_commons.map", EMBED_MAPS_ORZ_COMMONS_MAP });
// 	asset_list.Add({ "maps/orz_dusttown.map", EMBED_MAPS_ORZ_DUSTTOWN_MAP });
// 	asset_list.Add({ "maps/q1m1.map", EMBED_MAPS_Q1M1_MAP });
// 	asset_list.Add({ "maps/q2m1.map", EMBED_MAPS_Q2M1_MAP });
// 	asset_list.Add({ "maps/q2m2.map", EMBED_MAPS_Q2M2_MAP });
// 	asset_list.Add({ "maps/q2m3.map", EMBED_MAPS_Q2M3_MAP });
// 	asset_list.Add({ "maps/q3m1_genlock.map", EMBED_MAPS_Q3M1_GENLOCK_MAP });
// 	asset_list.Add({ "maps/q3m2_bandits.map", EMBED_MAPS_Q3M2_BANDITS_MAP });
// 	asset_list.Add({ "maps/q4m1.map", EMBED_MAPS_Q4M1_MAP });
// 	asset_list.Add({ "maps/q4m2.map", EMBED_MAPS_Q4M2_MAP });
// 	asset_list.Add({ "maps/q4m3.map", EMBED_MAPS_Q4M3_MAP });
// 	asset_list.Add({ "maps/q4m4.map", EMBED_MAPS_Q4M4_MAP });
// 	asset_list.Add({ "maps/tut_area.map", EMBED_MAPS_TUT_AREA_MAP });
 	asset_list.Add({ "maps/tut_area2.map", EMBED_MAPS_TUT_AREA2_MAP });
// 	asset_list.Add({ "assets/df_leather.swf", EMBED_ASSETS_DF_LEATHER_SWF });
// 	asset_list.Add({ "assets/df_mail.swf", EMBED_ASSETS_DF_MAIL_SWF });
// 	asset_list.Add({ "assets/dw_leather.swf", EMBED_ASSETS_DW_LEATHER_SWF });
// 	asset_list.Add({ "assets/dw_mail.swf", EMBED_ASSETS_DW_MAIL_SWF });
// 	asset_list.Add({ "assets/hf_cloth.swf", EMBED_ASSETS_HF_CLOTH_SWF });
// 	asset_list.Add({ "assets/hf_leather2.swf", EMBED_ASSETS_HF_LEATHER2_SWF });
// 	asset_list.Add({ "assets/hf_leather.swf", EMBED_ASSETS_HF_LEATHER_SWF });
// 	asset_list.Add({ "assets/hf_mail2.swf", EMBED_ASSETS_HF_MAIL2_SWF });
// 	asset_list.Add({ "assets/hf_mail.swf", EMBED_ASSETS_HF_MAIL_SWF });
// 	asset_list.Add({ "assets/hm_cloth.swf", EMBED_ASSETS_HM_CLOTH_SWF });
// 	asset_list.Add({ "assets/hm_leather2.swf", EMBED_ASSETS_HM_LEATHER2_SWF });
// 	asset_list.Add({ "assets/hm_leather.swf", EMBED_ASSETS_HM_LEATHER_SWF });
// 	asset_list.Add({ "assets/hm_mail2.swf", EMBED_ASSETS_HM_MAIL2_SWF });
// 	asset_list.Add({ "assets/hm_mail.swf", EMBED_ASSETS_HM_MAIL_SWF });
// 	asset_list.Add({ "assets/m_bandit.swf", EMBED_ASSETS_M_BANDIT_SWF });
// 	asset_list.Add({ "assets/m_deep_stalker.swf", EMBED_ASSETS_M_DEEP_STALKER_SWF });
// 	asset_list.Add({ "assets/m_genlock.swf", EMBED_ASSETS_M_GENLOCK_SWF });
// 	asset_list.Add({ "assets/m_hurlock.swf", EMBED_ASSETS_M_HURLOCK_SWF });
// 	asset_list.Add({ "assets/m_ogre.swf", EMBED_ASSETS_M_OGRE_SWF });
// 	asset_list.Add({ "assets/m_spider_giant.swf", EMBED_ASSETS_M_SPIDER_GIANT_SWF });
// 	asset_list.Add({ "tutorials.xml", EMBED_TUTORIALS_XML });
// 	asset_list.Add({ "convIDs.xml", EMBED_CONVIDS_XML });
 	asset_list.Add({ "gameData.xml", EMBED_GAMEDATA_XML });
// 	asset_list.Add({ "dialogues/conv_alldead.txt", EMBED_DIALOGUES_CONV_ALLDEAD_TXT });
// 	asset_list.Add({ "dialogues/conv_bandit2.txt", EMBED_DIALOGUES_CONV_BANDIT2_TXT });
// 	asset_list.Add({ "dialogues/conv_bandit.txt", EMBED_DIALOGUES_CONV_BANDIT_TXT });
// 	asset_list.Add({ "dialogues/conv_bard.txt", EMBED_DIALOGUES_CONV_BARD_TXT });
// 	asset_list.Add({ "dialogues/conv_bard2.txt", EMBED_DIALOGUES_CONV_BARD2_TXT });
// 	asset_list.Add({ "dialogues/conv_bard3.txt", EMBED_DIALOGUES_CONV_BARD3_TXT });
// 	asset_list.Add({ "dialogues/conv_bard_rejoin.txt", EMBED_DIALOGUES_CONV_BARD_REJOIN_TXT });
// 	asset_list.Add({ "dialogues/conv_captain.txt", EMBED_DIALOGUES_CONV_CAPTAIN_TXT });
// 	asset_list.Add({ "dialogues/conv_captain2.txt", EMBED_DIALOGUES_CONV_CAPTAIN2_TXT });
// 	asset_list.Add({ "dialogues/conv_commons_to_dusttown.txt", EMBED_DIALOGUES_CONV_COMMONS_TO_DUSTTOWN_TXT });
// 	asset_list.Add({ "dialogues/conv_crimelord2.txt", EMBED_DIALOGUES_CONV_CRIMELORD2_TXT });
// 	asset_list.Add({ "dialogues/conv_crimelord3.txt", EMBED_DIALOGUES_CONV_CRIMELORD3_TXT });
// 	asset_list.Add({ "dialogues/conv_crimelord4.txt", EMBED_DIALOGUES_CONV_CRIMELORD4_TXT });
// 	asset_list.Add({ "dialogues/conv_crimelord5.txt", EMBED_DIALOGUES_CONV_CRIMELORD5_TXT });
// 	asset_list.Add({ "dialogues/conv_crimelord_commons.txt", EMBED_DIALOGUES_CONV_CRIMELORD_COMMONS_TXT });
// 	asset_list.Add({ "dialogues/conv_dead_smugglers.txt", EMBED_DIALOGUES_CONV_DEAD_SMUGGLERS_TXT });
// 	asset_list.Add({ "dialogues/conv_dusttown.txt", EMBED_DIALOGUES_CONV_DUSTTOWN_TXT });
// 	asset_list.Add({ "dialogues/conv_emissary_mine.txt", EMBED_DIALOGUES_CONV_EMISSARY_MINE_TXT });
// 	asset_list.Add({ "dialogues/conv_emissary_mine_defeated.txt", EMBED_DIALOGUES_CONV_EMISSARY_MINE_DEFEATED_TXT });
// 	asset_list.Add({ "dialogues/conv_first_machine.txt", EMBED_DIALOGUES_CONV_FIRST_MACHINE_TXT });
// 	asset_list.Add({ "dialogues/conv_greywarden2.txt", EMBED_DIALOGUES_CONV_GREYWARDEN2_TXT });
// 	asset_list.Add({ "dialogues/conv_greywarden.txt", EMBED_DIALOGUES_CONV_GREYWARDEN_TXT });
// 	asset_list.Add({ "dialogues/conv_healer.txt", EMBED_DIALOGUES_CONV_HEALER_TXT });
// 	asset_list.Add({ "dialogues/conv_healer_rejoin.txt", EMBED_DIALOGUES_CONV_HEALER_REJOIN_TXT });
// 	asset_list.Add({ "dialogues/conv_leaving_orzammar_commons.txt", EMBED_DIALOGUES_CONV_LEAVING_ORZAMMAR_COMMONS_TXT });
// 	asset_list.Add({ "dialogues/conv_leaving_quest_area.txt", EMBED_DIALOGUES_CONV_LEAVING_QUEST_AREA_TXT });
// 	asset_list.Add({ "dialogues/conv_lowlysoldier2.txt", EMBED_DIALOGUES_CONV_LOWLYSOLDIER2_TXT });
// 	asset_list.Add({ "dialogues/conv_lowlysoldier3.txt", EMBED_DIALOGUES_CONV_LOWLYSOLDIER3_TXT });
// 	asset_list.Add({ "dialogues/conv_lowlysoldier4.txt", EMBED_DIALOGUES_CONV_LOWLYSOLDIER4_TXT });
// 	asset_list.Add({ "dialogues/conv_lowlysoldier.txt", EMBED_DIALOGUES_CONV_LOWLYSOLDIER_TXT });
// 	asset_list.Add({ "dialogues/conv_militaryleader2.txt", EMBED_DIALOGUES_CONV_MILITARYLEADER2_TXT });
// 	asset_list.Add({ "dialogues/conv_militaryleader3.txt", EMBED_DIALOGUES_CONV_MILITARYLEADER3_TXT });
// 	asset_list.Add({ "dialogues/conv_militaryleader.txt", EMBED_DIALOGUES_CONV_MILITARYLEADER_TXT });
// 	asset_list.Add({ "dialogues/conv_militaryleader_waiting_for_warden.txt", EMBED_DIALOGUES_CONV_MILITARYLEADER_WAITING_FOR_WARDEN_TXT });
// 	asset_list.Add({ "dialogues/conv_noble3.txt", EMBED_DIALOGUES_CONV_NOBLE3_TXT });
// 	asset_list.Add({ "dialogues/conv_noble2.txt", EMBED_DIALOGUES_CONV_NOBLE2_TXT });
// 	asset_list.Add({ "dialogues/conv_noble.txt", EMBED_DIALOGUES_CONV_NOBLE_TXT });
// 	asset_list.Add({ "dialogues/conv_noble_during_genlock_quest.txt", EMBED_DIALOGUES_CONV_NOBLE_DURING_GENLOCK_QUEST_TXT });
// 	asset_list.Add({ "dialogues/conv_origin2.txt", EMBED_DIALOGUES_CONV_ORIGIN2_TXT });
// 	asset_list.Add({ "dialogues/conv_origin.txt", EMBED_DIALOGUES_CONV_ORIGIN_TXT });
// 	asset_list.Add({ "dialogues/conv_pub2.txt", EMBED_DIALOGUES_CONV_PUB2_TXT });
// 	asset_list.Add({ "dialogues/conv_pub.txt", EMBED_DIALOGUES_CONV_PUB_TXT });
// 	asset_list.Add({ "dialogues/conv_punk_dust.txt", EMBED_DIALOGUES_CONV_PUNK_DUST_TXT });
// 	asset_list.Add({ "dialogues/conv_scene4.txt", EMBED_DIALOGUES_CONV_SCENE4_TXT });
// 	asset_list.Add({ "dialogues/conv_search.txt", EMBED_DIALOGUES_CONV_SEARCH_TXT });
// 	asset_list.Add({ "dialogues/conv_second_machine.txt", EMBED_DIALOGUES_CONV_SECOND_MACHINE_TXT });
// 	asset_list.Add({ "dialogues/conv_third_machine.txt", EMBED_DIALOGUES_CONV_THIRD_MACHINE_TXT });
// 	asset_list.Add({ "dialogues/conv_tooweak.txt", EMBED_DIALOGUES_CONV_TOOWEAK_TXT });
// 	asset_list.Add({ "dialogues/conv_tutorial2.txt", EMBED_DIALOGUES_CONV_TUTORIAL2_TXT });
// 	asset_list.Add({ "dialogues/conv_tutorial.txt", EMBED_DIALOGUES_CONV_TUTORIAL_TXT });
// 	asset_list.Add({ "dialogues/conv_warden_rejoin.txt", EMBED_DIALOGUES_CONV_WARDEN_REJOIN_TXT });
// 	asset_list.Add({ "dialogues/innkeeper_commons.txt", EMBED_DIALOGUES_INNKEEPER_COMMONS_TXT });
// 	asset_list.Add({ "dialogues/innkeeper_dust.txt", EMBED_DIALOGUES_INNKEEPER_DUST_TXT });
// 	asset_list.Add({ "dialogues/shop_commons_blacksmith.txt", EMBED_DIALOGUES_SHOP_COMMONS_BLACKSMITH_TXT });
// 	asset_list.Add({ "dialogues/shop_commons_stall.txt", EMBED_DIALOGUES_SHOP_COMMONS_STALL_TXT });
// 	asset_list.Add({ "dialogues/shop_commons_potions.txt", EMBED_DIALOGUES_SHOP_COMMONS_POTIONS_TXT });
// 	asset_list.Add({ "dialogues/shop_dust_blacksmith.txt", EMBED_DIALOGUES_SHOP_DUST_BLACKSMITH_TXT });
// 	asset_list.Add({ "dialogues/shop_dust_stall.txt", EMBED_DIALOGUES_SHOP_DUST_STALL_TXT });

#ifdef DEBUG
	FString sString = "Embedded Assets";
	UE_LOG(LogTemp, Warning, TEXT("%i - %s"), asset_list.Num(), *sString);
#endif // DEBUG
}

UEmbedList::~UEmbedList()
{
}
