#pragma once

const FString MALE_STRING = "Men and women in Ferelden are generally regarded as equals. Both genders are evenly represented in most organizations, noble houses and military forces.";
const FString FEMALE_STRING = "Men and women in Ferelden are generally regarded as equals. Both genders are evenly represented in most organizations, noble houses and military forces.";
const FString WARRIOR_STRING = "Warriors are powerful fighters, focusing on melee and ranged weapons to deal with their foes. They can withstand and deliver a great deal of punishment, and have a strong understanding of tactics and strategy.";
const FString ROGUE_STRING = "Rogues are skilled adventurers who come from all walks of life. Tactically, they are not ideal front-line fighters, but if rogues can circle around behind their target, they can backstab to devastating effect.";
const FString MAGE_STRING = "As dangerous as it is potent, magic is a curse for those lacking the will to wield it. Malevolent spirits that wish to enter the world of the living are drawn to mages like beacons, putting the mage and everyone nearby in constant danger. Because of this, mages lead lives of isolation, locked away from the world they threaten.";
const FString HUMAN_NOBLE_STRING = "Your father - a lesser noble in King Maric’s court - has been sent to Orzammar on a diplomatic task. Although privileged, your father always looks for avenues to increased wealth. In Orzammar he has found merchants offering great opportunity, but must meet them outside the city for fear of being overheard.";
const FString ELF_DALISH_STRING = "The Dalish elders, holders of great knowledge and skill, fear that a darkspawn threat may be growing.  They have sent you and your brother to the Deep Roads to find out more.  The elders hope that this envoy will also be seen as a token of good will by the dwarves of Orzammar.";
const FString ELF_CITY_STRING = "You and your sister live hard lives as servants to a petty and cruel merchant who has traveled to Orzammar for business.  You head into the Deep Roads with him and a hired hand so that he may close a deal away from prying eyes and ears.";
const FString DWARF_NOBLE_STRING = "In Orzammar, political machinations and overly ambitious deeds can lead to a noble family\'s swift fall from grace.  Such a sad fate fell upon your house thanks to a foolish uncle.  To regain your social standing you and your two brothers travel to the Deep Roads looking for battle and glory.";
const FString DWARF_COMMONER_STRING = "Born into the merchant caste, you\'ve always felt that your true fate was to be a soldier. To follow your dreams, you have forsaken friends and family, traveling the Deep Roads outside Orzammar to join the ranks.";
const FString MAGE_ORIGIN_STRING = "Under the omnipresent eye of the Chanty, you have trained with the Circle of Magi since childhood.  Your mentor of many years has brought you to the Deep Roads to complete the final task of your training.";
const FString HUMAN_STRING = "The most numerous, yet the most divided of all the races. Only four times have they ever united under a single cause, the last being centuries ago. Religion and the Chantry play a large part in human society. It distinguishes them culturally from elves and dwarves more than anything else.";
const FString ELF_STRING = "Once enslaved by humans, most elves have all but lost their culture, scrounging an impoverished living in the slums of human cities. Only the nomadic Dalish tribes still cling to their traditions, living by the bow and the rule of their old gods as they roam the ancient forests, welcome nowhere else.";
const FString DWARF_STRING = "Rigidly bound by caste and tradition, the dwarves have been waging a losing war for generations, trying to protect the last stronghold of their once vast underground empire from the darkspawn. Dwarves are very tough and have a high resistance to all forms of magic, thus preventing them from becoming mages.";
